# Generated by Django 2.2.6 on 2021-06-14 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20210613_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='client',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='sub',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follow_follower', to='users.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
